# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e1deba8c49e06faafc4c0d356daf9c35dc0e15e031935c1fdc64e2ffd63632d7a22cacb0f96b22155eedd2341669505b019d95284d2f40ba99aa8a846e44ef

test:
  secret_key_base: 9c2b012a19f41c8c1790f8de76da661dbf3c9c2caeaca8c0df775f8bfe35e6cc4df066d6697d2aa4664b2488a7ad5d4043c5f2dc92c0a5236fdc991c4e7fb14f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
